# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef3b805a325138640ca7fa207554fdb4449d77291ccb301b3d2ea4785170c28c42f9e645304fe940f9acdc4ccb2d64dc6851ab77c233872acb37a507e5130313

test:
  secret_key_base: 08f569a7b0e8af14f1254db75b46f962856a0560657f9227dd3452d841bc56d5e238238aa97e507ddc112ee5f93ea471f5732aaa1f7335f19eb151d614a6a8f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
